steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/avdhut-notes-backend:latest', './backend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/avdhut-notes-backend:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform', 'linux/amd64', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/avdhut-notes-frontend:latest', './frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID/$_REPO/avdhut-notes-frontend:latest']
options:
    logging: 'CLOUD_LOGGING_ONLY'